import 'package:myapp_ecommerce/modal/products.dart';

final List<Products> productsList = [
  Products(
    imageUrl: 'assets/product/p1.jpeg',
    title: 'Premium Slim Fit Beige Color Twill Pant',
    price: '\$102',
    originalPrice: '\$199',
    discount: '15% OFF',
    rating: '4.3',
    reviewCount: '41',
    isNew: true,
    thumbnailImages: [
      'assets/product/pth1.png',
      'assets/product/pth2.png',
      'assets/product/pth3.png',
      'assets/product/pth3.png',
    ],
    description: 'This is a premium slim-fit pant...',
    information: [
      'Fabric: Cotton',
      'Fit: Slim',
      'Color: Beige',
    ],
    productDetails: 'Detailed product description goes here.',
    shippingInfo: 'Ships within 3-5 business days.',
    returnsPolicy: 'Free returns within 30 days.',
  ),
  Products(
    imageUrl: 'assets/product/p2.jpeg',
    title: 'Casual Shirt for Men',
    price: '\$50',
    originalPrice: '\$75',
    discount: '33% OFF',
    rating: '4.5',
    reviewCount: '89',
    isNew: false,
    thumbnailImages: [
      'assets/product/pth1.png',
      'assets/product/pth3.png',
      'assets/product/pth2.png',
      'assets/product/pth2.png',
    ],
    description: 'A comfortable and stylish shirt...',
    information: [
      'Fabric: Linen',
      'Fit: Regular',
      'Color: White',
    ],
    productDetails: 'Perfect for daily casual wear.',
    shippingInfo: 'Ships within 2-3 business days.',
    returnsPolicy: 'Free returns within 30 days.',
  ),
  Products(
    imageUrl: 'assets/product/p3.png',
    title: 'Women’s Elegant Dress',
    price: '\$120',
    originalPrice: '\$180',
    discount: '20% OFF',
    rating: '4.7',
    reviewCount: '67',
    isNew: true,
    thumbnailImages: [
      'assets/product/pth7.png',
      'assets/product/pth8.png',
      'assets/product/pth9.png',
      'assets/product/pth9.png',
    ],
    description: 'An elegant dress perfect for events...',
    information: [
      'Fabric: Silk',
      'Fit: Slim',
      'Color: Red',
    ],
    productDetails: 'Makes a statement at any occasion.',
    shippingInfo: 'Ships within 4-6 business days.',
    returnsPolicy: 'Free returns within 14 days.',
  ),
  // Products(
  //   imageUrl: 'assets/product/p4.png',
  //   title: 'Leather Boots',
  //   price: '\$150',
  //   originalPrice: '\$200',
  //   discount: '25% OFF',
  //   rating: '4.4',
  //   reviewCount: '53',
  //   isNew: false,
  //   thumbnailImages: [
  //     'assets/product/pth10.png',
  //     'assets/product/pth11.png',
  //     'assets/product/pth12.png',
  //   ],
  //   description: 'Durable and stylish leather boots...',
  //   information: [
  //     'Material: Genuine Leather',
  //     'Color: Black',
  //   ],
  //   productDetails: 'Great for both casual and formal wear.',
  //   shippingInfo: 'Ships within 3-4 business days.',
  //   returnsPolicy: 'Free returns within 30 days.',
  // ),
  // Products(
  //   imageUrl: 'assets/product/p5.png',
  //   title: 'Sports Sneakers',
  //   price: '\$80',
  //   originalPrice: '\$120',
  //   discount: '10% OFF',
  //   rating: '4.2',
  //   reviewCount: '77',
  //   isNew: true,
  //   thumbnailImages: [
  //     'assets/product/pth13.png',
  //     'assets/product/pth14.png',
  //     'assets/product/pth15.png',
  //   ],
  //   description: 'Comfortable sneakers for sports...',
  //   information: [
  //     'Material: Mesh Fabric',
  //     'Color: Grey',
  //   ],
  //   productDetails: 'Ideal for running and training.',
  //   shippingInfo: 'Ships within 1-3 business days.',
  //   returnsPolicy: 'Free returns within 15 days.',
  // ),
  // Products(
  //   imageUrl: 'assets/product/p6.png',
  //   title: 'Formal Wrist Watch',
  //   price: '\$200',
  //   originalPrice: '\$300',
  //   discount: '33% OFF',
  //   rating: '4.8',
  //   reviewCount: '128',
  //   isNew: false,
  //   thumbnailImages: [
  //     'assets/product/pth16.png',
  //     'assets/product/pth17.png',
  //     'assets/product/pth18.png',
  //   ],
  //   description: 'A luxury watch for formal occasions...',
  //   information: [
  //     'Material: Stainless Steel',
  //     'Color: Silver',
  //   ],
  //   productDetails: 'High-quality craftsmanship and durability.',
  //   shippingInfo: 'Ships within 2-5 business days.',
  //   returnsPolicy: 'Free returns within 30 days.',
  // )
];
